### ISSUE TITLE
LICENSE

### ISSUE THREAD

**Issue by C4Phone** [TakefiveInteractive/TedkOS#69]

**Comment by Tedko** [comment]
How about Apache 2.0

**Comment by Tedko** [comment]
We should also note that programs like pingpong is given by TA. (property of ece dept)

**Comment by C4Phone** [comment]
But we are also using newlibs and Boost. Newlibs has a GPLv2 license, and Boost has its own license too.

**Comment by Tedko** [comment]
well, since 
> 'Any modifications to or software including (via compiler) GPL-licensed code must also be made available under the GPL along with build & install instructions.'

Also,
> Boost is licensed under its own free, open-source license, known as the Boost Software License. It is a permissive license in the style of the BSD license and the MIT license. The license has been OSI-approved since February 2008[5][6] and is considered a free software license, compatible with the GNU General Public License, by the Free Software Foundation.[7]

Lets make it GPLv2 .

**Comment by Tedko** [comment]
added.

**Comment by Tedko** [comment]
For TA's code, I will add sth on readme
